config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "user_sessions#new"
  resource :user_sessions do
    get :new
    get :success
  end
  
  resources :users, only: [:new, :create] do
    resources :comments
    resources :feed, only: [:show]
    resources :profile, only: [:show, :index, :edit, :update]
    resources :posts, only: [:create]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/feed.rb
class Feed < ApplicationRecord
  belongs_to :profile
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :feed
  belongs_to :user
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one :feed
  
  def full_name
    "#{self.first_name} #{self.last_name}".split.map(&:capitalize).join(' ')
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_one :profile
  has_one :feed, through: :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comments_params)
    @post = Post.find(comments_params[:post_id])
    @post_comments = @post.comments
    #todo  Render as Js with create.js.erb
    redirect_to user_feed_path(id: current_user.id, feed_id: params[:id])
  end
  
  def destroy
    comment = Comment.find(params[:comment_id])
    comment.delete
    redirect_to user_feed_path(id: current_user.id, feed_id: params[:id])
  end
  
  private
  def comments_params
    params.require(:comment).permit(:body, :user_id, :post_id)
  end
  
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def show
    @facade = Feed::FeedShowFacade.new(current_user: current_user)
  end
  
  def index
    # If profile relationships were made use something like this:
    # @posts = Profile.following_posts
    # and scope the following_posts query out on the model to get all 
    # the recent posts from who they are following
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def create
      post = Post.create(
        user_id: params[:user_id],
        feed_id: params[:feed_id]
      )
      post.image.attach(post_params[:image])
      redirect_to user_feed_path(id: params[:feed_id])
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
  
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def show
    @profile = Profile.find(params[:id])
  end

  private
  def profile_params
      params.require(:profile).permit(:first_name, :last_name)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    redirect_to user_feed_path(user_id: current_user.id ,id: current_user.feed.id) if logged_in?
  end

  def create
    @user = login(params[:email].downcase, params[:password])
    return failed_login unless @user
    redirect_to user_feed_path(user_id: current_user.id, id: current_user.feed.id)
  end

  def destroy
    logout
    flash[:warning] = "Logged out!"
    redirect_to new_user_sessions_path
  end

  def failed_login
    @failed_login = true
    render action: 'new'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  
  def new
  end
  
  def create
    user = Users::UserCreateFacade.new(
      email: params[:email],
      password: params[:password],
      first_name: params[:first_name],
      last_name: params[:last_name],
    ).run
    
    redirect_to user_sessions_path

    rescue Users::UserCreateFacade::UserAlreadyExists
      redirect_to new_user_sessions_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.js.erb
$("#post-comments<%= @post.id %>").html(
  "<%= j render 'shared/post_comments', 
  post_comments: @post_comments %>"
);

app/views/feed/_feed_post_form.html.erb
<%= form_for @post, url: user_posts_path(id: 1, feed_id: 1) do |f| %>
  <div>
    <%= label_tag :image, 'Add image' %><br />
    <%= f.file_field :image %>
  </div>
<%= f.submit "Create post" %>
<% end %>

app/views/feed/show.html.erb
<%= form_for @facade.new_post, url: user_posts_path(id: current_user.id, feed_id: current_user.feed.id) do |f| %>
  <div>
    <%= label_tag :image, 'Add image' %><br />
    <%= f.file_field :image %>
  </div>
<%= f.submit "Create post" %>
<% end %>

<% @facade.posts.each do |post| %>
  <div>
    <div>
      <%= image_tag(post.image) if post.image %>
      <ruby>
        <rt><%= post[:first_name] %> <%= post[:last_name] %></rt>
      </ruby>
    </div>
  
  <div id="post-comments">
    <%= render "shared/post_comments", post_comments: post.comments, user_id: current_user.id, feed_id: params[:id] %>
  </div>
    
    <%= form_for @facade.new_comment, url: user_comments_path(user_id: current_user.id, post_id: post.id), html: {id: "post-#{post.id}"}, format: :js, authenticity_token: true, remote: true do |f| %>
      <div>
        <%= label_tag :body, 'Comment' %><br />
        <%= f.text_area :body %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :post_id, value: post.id %>
      </div>
    <%= f.submit "Post" %>
    <% end %>
    
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netengine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_post_comments.html.erb
<% post_comments.each do |comment| %>
  <p><%= comment.body %></p>
  <%= button_to "delete", user_comment_path(comment_id: comment.id, user_id: user_id, feed_id: feed_id), class: "", method: "delete", remote: true %>
<% end %>

app/views/user_sessions/new.html.erb
<% if @failed_login %>
  <p> Email/Password is incorrect </p>
<% end %>
<%= form_tag user_sessions_path, method: :post do %>
  <div>
      <%= label_tag :email, 'Email'%><br />
      <%= text_field_tag :email,'', class: '', required: true, autofocus: true %>
  </div>
  <div>
    <%= label_tag :password, 'Password', class: '' %><br />
    <%= password_field_tag :password,'' , class: '', required: true %>
  </div>
  <div>
    <div>
      <%= link_to 'Sign up', new_user_path %>
      <%= button_tag do %>
        Login
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
  <%= form_tag users_path, method: :post do %>
    <div>
        <%= label_tag :email, 'Email', class: '' %><br />
        <%= text_field_tag :email,'', class: '', required: true, autofocus: true %>
      </div>

    <div>
        <%= label_tag :password, 'Password', class: '' %><br />
        <%= password_field_tag :password,'' , class: '', required: true %>
      </div>

      <div>
          <%= label_tag :first_name, 'First Name', class: '' %><br />
          <%= text_field_tag :first_name,'', class: '', required: true, autofocus: true %>
        </div>

    <div>
      <%= label_tag :last_name, 'Last Name', class: '' %><br />
      <%= text_field_tag :last_name,'', class: '', required: true, autofocus: true %>
    </div>

    <div>
        <%= link_to 'Log In', user_sessions_path %>
        <%= button_tag do %>
          Create Account
        <% end %>
      </div>
  <% end %>